-- =============================================================================
-- CHRONOSCOPE — Database Schema
-- =============================================================================
-- This SQL script initializes the PostgreSQL Event Store with all tables
-- required for the replay engine system.
--
-- TABLES:
--   1. events              → Core event store (all events from all services)
--   2. processed_events    → Idempotency tracking (prevents duplicate processing)
--   3. replay_sessions     → Replay audit log (tracks every replay execution)
--   4. orders              → Order service domain table
--   5. payments            → Payment service domain table
--
-- DESIGN DECISIONS:
--   - JSONB for payload: Flexible schema, supports deep querying with GIN index
--   - Composite indexes on (correlation_id, timestamp): Optimized for timeline queries
--   - UUID primary keys: Globally unique, no coordination needed between services
--   - BIGINT timestamps: Unix epoch milliseconds for consistent cross-service ordering
--
-- USAGE:
--   This file is auto-executed by PostgreSQL on first container startup
--   (mounted to /docker-entrypoint-initdb.d/)
-- =============================================================================

-- =============================================================================
-- TABLE: events
-- =============================================================================
-- The HEART of the system. Every event from every service is stored here.
--
-- This table enables:
--   - Timeline reconstruction (query by correlation_id, ORDER BY timestamp)
--   - Failure analysis (filter by event_type containing 'FAILED')
--   - Service-level debugging (filter by service name)
--   - Replay input (fetch ordered events for re-execution)
--
-- WHY JSONB FOR PAYLOAD?
--   - Different event types have different payloads
--   - We can still query into the payload: payload->>'orderId'
--   - GIN index enables efficient JSONB searching
--   - No schema migration needed when adding new event fields
--

-- =============================================================================
CREATE TABLE IF NOT EXISTS events (
    -- Unique identifier for each event (UUID v4)
    -- Generated by the producing service to ensure global uniqueness
    event_id        TEXT PRIMARY KEY,

    -- Correlation ID ties together ALL events from a single request flow
    -- Example: User places order → ORDER_CREATED → PAYMENT_INITIATED → PAYMENT_SUCCESS
    -- All of these share the same correlation_id
    -- THIS IS THE MOST IMPORTANT FIELD FOR DEBUGGING
    correlation_id  TEXT NOT NULL,

    -- Type of event — follows ENTITY_ACTION naming convention
    -- Examples: ORDER_CREATED, PAYMENT_INITIATED, PAYMENT_SUCCESS, PAYMENT_FAILED
    event_type      TEXT NOT NULL,

    -- Name of the service that produced this event
    -- Used for filtering and timeline visualization
    -- Examples: order-service, payment-service
    service         TEXT NOT NULL,

    -- Unix timestamp in milliseconds when the event was created
    -- Using milliseconds (not seconds) for sub-second ordering precision
    -- CRITICAL: This determines replay order
    timestamp       BIGINT NOT NULL,

    -- Full event payload as JSONB
    -- Contains all domain-specific data (order details, payment amounts, etc.)
    -- JSONB enables indexed queries without schema constraints
    payload         JSONB DEFAULT '{}',

    -- Metadata for tracking event lineage
    -- Stores: source_topic, partition, offset, producer_ip, etc.
    metadata        JSONB DEFAULT '{}',

    -- When was this event ingested into the event store
    -- Different from `timestamp` (event creation time) — captures ingestion delay
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index: Fast timeline reconstruction by correlation_id
-- This is the PRIMARY query pattern: "Give me all events for this request"
-- Composite with timestamp for ordered retrieval
CREATE INDEX IF NOT EXISTS idx_events_correlation_id 
    ON events (correlation_id, timestamp ASC);

-- Index: Filter events by type (e.g., "show me all PAYMENT_FAILED events")
CREATE INDEX IF NOT EXISTS idx_events_event_type 
    ON events (event_type);

-- Index: Filter events by service (e.g., "show me all order-service events")
CREATE INDEX IF NOT EXISTS idx_events_service 
    ON events (service);

-- Index: Time-range queries (e.g., "show me events from the last hour")
CREATE INDEX IF NOT EXISTS idx_events_timestamp 
    ON events (timestamp DESC);

-- Index: Full-text search within JSONB payload
-- Enables queries like: WHERE payload @> '{"orderId": "ord-123"}'
CREATE INDEX IF NOT EXISTS idx_events_payload 
    ON events USING GIN (payload);


-- =============================================================================
-- TABLE: processed_events
-- =============================================================================
-- IDEMPOTENCY TABLE — Prevents duplicate event processing during replay.
--
-- WHY IS THIS CRITICAL?
--   - During replay, the same event may be re-processed multiple times
--   - Without idempotency, you'd double-charge customers, send duplicate emails
--   - Before processing ANY event, check: "Have I already processed this?"
--
-- DUAL STORAGE STRATEGY:
--   - Redis (hot path): O(1) lookups during replay for speed
--   - PostgreSQL (cold path): Persistent record for audit and recovery
--

-- =============================================================================
CREATE TABLE IF NOT EXISTS processed_events (
    -- The event_id that was processed
    event_id        TEXT PRIMARY KEY,

    -- Which service processed this event
    processed_by    TEXT NOT NULL,

    -- When was this event processed
    processed_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Processing result (SUCCESS, FAILED, SKIPPED)
    result          TEXT DEFAULT 'SUCCESS',

    -- Optional: error message if processing failed
    error_message   TEXT
);

-- Index: Find all events processed by a specific service
CREATE INDEX IF NOT EXISTS idx_processed_events_service 
    ON processed_events (processed_by);


-- =============================================================================
-- TABLE: replay_sessions
-- =============================================================================
-- AUDIT LOG for all replay executions.
--
-- Every time an engineer triggers a replay, we record:
--   - What was replayed (correlation_id)
--   - How it was replayed (mode: dry-run vs state-rebuild)
--   - What happened (status, events processed, errors)
--   - Who triggered it (triggered_by)
--
-- This is essential for:
--   - Debugging the debugger (if replay itself fails)
--   - Compliance/audit (who replayed what, when)
--   - Performance tracking (replay latency trends)
-- =============================================================================
CREATE TABLE IF NOT EXISTS replay_sessions (
    -- Unique replay session identifier
    session_id      TEXT PRIMARY KEY,

    -- Which request flow is being replayed
    correlation_id  TEXT NOT NULL,

    -- Replay mode: 'dry-run' (safe, no writes) or 'state-rebuild' (recreates state)
    mode            TEXT NOT NULL DEFAULT 'dry-run',

    -- Current status: PENDING, RUNNING, COMPLETED, FAILED
    status          TEXT NOT NULL DEFAULT 'PENDING',

    -- Total number of events in this replay
    total_events    INTEGER DEFAULT 0,

    -- How many events have been replayed so far (for progress tracking)
    processed_count INTEGER DEFAULT 0,

    -- How many events were skipped (already processed / idempotent)
    skipped_count   INTEGER DEFAULT 0,

    -- How many events failed during replay
    failed_count    INTEGER DEFAULT 0,

    -- Detailed results for each event replayed
    results         JSONB DEFAULT '[]',

    -- Who triggered this replay (engineer name/ID)
    triggered_by    TEXT DEFAULT 'system',

    -- Timing
    started_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at    TIMESTAMP WITH TIME ZONE,

    -- Error details if the replay session itself failed
    error           TEXT
);

-- Index: Find replay sessions by correlation_id
CREATE INDEX IF NOT EXISTS idx_replay_sessions_correlation 
    ON replay_sessions (correlation_id);

-- Index: Find recent replay sessions
CREATE INDEX IF NOT EXISTS idx_replay_sessions_started 
    ON replay_sessions (started_at DESC);


-- =============================================================================
-- TABLE: orders
-- =============================================================================
-- Domain table for the Order Service.
-- Stores the current state of orders (the "write model").
-- During replay in state-rebuild mode, this table gets recreated from events.
-- =============================================================================
CREATE TABLE IF NOT EXISTS orders (
    -- Order identifier
    order_id        TEXT PRIMARY KEY,

    -- Customer who placed the order
    customer_id     TEXT NOT NULL,

    -- Order items as JSONB array
    items           JSONB DEFAULT '[]',

    -- Total order amount in cents (avoid floating point for money!)
    total_amount    INTEGER NOT NULL DEFAULT 0,

    -- Order status: PENDING, CONFIRMED, PAID, SHIPPED, CANCELLED
    status          TEXT NOT NULL DEFAULT 'PENDING',

    -- Correlation ID linking to the original request
    correlation_id  TEXT,

    -- Timestamps
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index: Find orders by customer
CREATE INDEX IF NOT EXISTS idx_orders_customer 
    ON orders (customer_id);

-- Index: Find orders by correlation_id (for replay verification)
CREATE INDEX IF NOT EXISTS idx_orders_correlation 
    ON orders (correlation_id);


-- =============================================================================
-- TABLE: payments
-- =============================================================================
-- Domain table for the Payment Service.
-- Tracks payment attempts and their outcomes.
-- =============================================================================
CREATE TABLE IF NOT EXISTS payments (
    -- Payment identifier
    payment_id      TEXT PRIMARY KEY,

    -- Which order this payment is for
    order_id        TEXT NOT NULL,

    -- Payment amount in cents
    amount          INTEGER NOT NULL DEFAULT 0,

    -- Payment status: INITIATED, PROCESSING, SUCCESS, FAILED, REFUNDED
    status          TEXT NOT NULL DEFAULT 'INITIATED',

    -- Payment method (CREDIT_CARD, DEBIT_CARD, UPI, etc.)
    payment_method  TEXT DEFAULT 'CREDIT_CARD',

    -- Correlation ID linking to the original request
    correlation_id  TEXT,

    -- Timestamps
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index: Find payments by order
CREATE INDEX IF NOT EXISTS idx_payments_order 
    ON payments (order_id);

-- Index: Find payments by correlation_id
CREATE INDEX IF NOT EXISTS idx_payments_correlation 
    ON payments (correlation_id);


-- =============================================================================
-- VIEWS — Pre-built queries for common debugging scenarios
-- =============================================================================

-- View: Event timeline for a correlation ID (most common debug query)
-- Usage: SELECT * FROM event_timeline WHERE correlation_id = 'req-123';
CREATE OR REPLACE VIEW event_timeline AS
SELECT 
    e.event_id,
    e.correlation_id,
    e.event_type,
    e.service,
    e.timestamp,
    -- Calculate time delta from the first event in the flow
    e.timestamp - MIN(e.timestamp) OVER (PARTITION BY e.correlation_id) AS time_delta_ms,
    e.payload,
    -- Check if this event has been processed (for replay tracking)
    CASE WHEN pe.event_id IS NOT NULL THEN true ELSE false END AS is_processed
FROM events e
LEFT JOIN processed_events pe ON e.event_id = pe.event_id
ORDER BY e.correlation_id, e.timestamp ASC;


-- View: Failure summary (quick overview of recent failures)
CREATE OR REPLACE VIEW failure_summary AS
SELECT 
    correlation_id,
    service,
    event_type,
    timestamp,
    payload->>'error' AS error_message,
    created_at
FROM events
WHERE event_type LIKE '%FAILED%'
   OR event_type LIKE '%ERROR%'
ORDER BY timestamp DESC
LIMIT 100;


-- =============================================================================
-- SEED DATA (Optional — uncomment for quick testing)
-- =============================================================================
-- INSERT INTO events (event_id, correlation_id, event_type, service, timestamp, payload)
-- VALUES 
--   ('evt-001', 'req-123', 'ORDER_CREATED', 'order-service', 1710000000000, 
--    '{"orderId": "ord-001", "customerId": "cust-001", "items": [{"name": "Widget", "qty": 2, "price": 999}], "totalAmount": 1998}'),
--   ('evt-002', 'req-123', 'PAYMENT_INITIATED', 'payment-service', 1710000001000, 
--    '{"paymentId": "pay-001", "orderId": "ord-001", "amount": 1998, "method": "CREDIT_CARD"}'),
--   ('evt-003', 'req-123', 'PAYMENT_SUCCESS', 'payment-service', 1710000002000, 
--    '{"paymentId": "pay-001", "orderId": "ord-001", "transactionRef": "txn-abc123"}');
